### ISSUE TITLE
AssertionError: The model is not fully loaded.

### ISSUE THREAD

**Issue by harrytrinh96** [sungonce/SENet#1]
Hi! Nice work. 
When I ran `python test.py SENET.RESNET_DEPTH 101 TEST.WEIGHTS pretrained_weights/SENet_R101_con.pt  TEST.DATA_DIR datadir_examples`
There was a mismatching error between weight_dict and state_dict. That is why I wasn't able to load the checkpoint
```

Traceback (most recent call last):
  File "test.py", line 16, in <module>
    main()
  File "test.py", line 13, in main
    SENet_tester.__main__()
  File "/mount/sdc2_10TB/harry/tensorboard_embeddings/SENet/core/SENet_tester.py", line 30, in __main__
    checkpoint.load_checkpoint(cfg.TEST.WEIGHTS, model)
  File "/mount/sdc2_10TB/harry/tensorboard_embeddings/SENet/core/checkpoint.py", line 45, in load_checkpoint
    raise AssertionError("The model is not fully loaded.")
AssertionError: The model is not fully loaded.

```
@sungonce

**Comment by yayaYsmile** [comment]
> 你好！干得不错。当我跑步时，weight_dict和state_dict之间出现了不匹配的错误。这就是为什么我无法加载检查点的原因`python test.py SENET.RESNET_DEPTH 101 TEST.WEIGHTS pretrained_weights/SENet_R101_con.pt TEST.DATA_DIR datadir_examples`
> 
> ```
> 
> Traceback (most recent call last):
>   File "test.py", line 16, in <module>
>     main()
>   File "test.py", line 13, in main
>     SENet_tester.__main__()
>   File "/mount/sdc2_10TB/harry/tensorboard_embeddings/SENet/core/SENet_tester.py", line 30, in __main__
>     checkpoint.load_checkpoint(cfg.TEST.WEIGHTS, model)
>   File "/mount/sdc2_10TB/harry/tensorboard_embeddings/SENet/core/checkpoint.py", line 45, in load_checkpoint
>     raise AssertionError("The model is not fully loaded.")
> AssertionError: The model is not fully loaded.
> ```
> 
> @sungonce

I have the same problem. Have you solved it?

**Comment by harrytrinh96** [comment]
I think the model we loaded and the target model are not identical...so that's why

**Comment by sungonce** [comment]
We fixed the error and updated the code. Please try again.
